
﻿// <auto-generated />
using System;
using Agent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Agent.Infrastructure.Migrations
{
    [DbContext(typeof(AgentDbContext))]
    partial class AgentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Agent.Domain.Entities.AgentAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("agent_audits", (string)null);
                });

            modelBuilder.Entity("Agent.Domain.Entities.AgentDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("MemoryEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MemoryInstructions")
                        .HasColumnType("text");

                    b.Property<string>("MemoryRetention")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MemoryScope")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelNameCache")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerUsername")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Status");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("Agent.Domain.Entities.AgentGroup", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.HasKey("AgentId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("agent_groups", (string)null);
                });

            modelBuilder.Entity("Agent.Domain.Entities.AgentKnowledgeBase", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KnowledgeBaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("KnowledgeBaseNameCache")
                        .HasColumnType("text");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("AgentId", "KnowledgeBaseId");

                    b.ToTable("agent_knowledge_bases", (string)null);
                });

            modelBuilder.Entity("Agent.Domain.Entities.AgentTool", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToolType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ToolNameCache")
                        .HasColumnType("text");

                    b.HasKey("AgentId", "ToolId", "ToolType");

                    b.ToTable("agent_tools", (string)null);
                });

            modelBuilder.Entity("Agent.Domain.Entities.AgentAudit", b =>
                {
                    b.HasOne("Agent.Domain.Entities.AgentDefinition", "Agent")
                        .WithMany("Audits")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Agent.Domain.Entities.AgentGroup", b =>
                {
                    b.HasOne("Agent.Domain.Entities.AgentDefinition", "Agent")
                        .WithMany("AgentGroups")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Agent.Domain.Entities.AgentKnowledgeBase", b =>
                {
                    b.HasOne("Agent.Domain.Entities.AgentDefinition", "Agent")
                        .WithMany("AgentKnowledgeBases")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Agent.Domain.Entities.AgentTool", b =>
                {
                    b.HasOne("Agent.Domain.Entities.AgentDefinition", "Agent")
                        .WithMany("AgentTools")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Agent.Domain.Entities.AgentDefinition", b =>
                {
                    b.Navigation("AgentGroups");

                    b.Navigation("AgentKnowledgeBases");

                    b.Navigation("AgentTools");

                    b.Navigation("Audits");
                });
#pragma warning restore 612, 618
        }
    }
}
